<?php
$UPLOADS="uploads/";
$PRODUCTS=array(
array("id"=>101,"image"=>"football.png","price"=>150),
array("id"=>102,"image"=>"tennis.png","price"=>120),
array("id"=>103,"image"=>"basketball.png","price"=>90),
array("id"=>104,"image"=>"table-tennis.png","price"=>110),
array("id"=>105,"image"=>"soccer.png","price"=>180)
);
?>